### PR TITLE
Remove `get_bcs` in `MeshSeq`

### LINKED ISSUE #167: Passing boundary conditions to MeshSeq
Since boundary conditions are only used in the solver, it seems unnecessary to define a `get_bcs` function and then passing it to the mesh sequence. Especially when prescribing bcs can be done with a single/few lines of code within the solver.

@jwallwork23 what do you think? I think that removing this would simplify the demos and declutter the goalie code.

### PR DESCRIPTION
**Pull request by ddundo**
Closes #167.

To simplify demos and Goalie itself, with this PR we no longer allow setting boundary conditions via a `get_bcs` kwarg to `MeshSeq`.

### CODE REVIEW

**Review by jwallwork23 — APPROVED** [review]
Thanks @ddundo. I'm happy if @acse-ej321 is.

Note I removed the PR from the project board. I decided to only put issues on it (see https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Development-Practices#mesh-adaptation-development-board).

**Comment by ddundo** [comment]
Thanks @jwallwork23! And one more thing... Does this also address #140? The issue mentions `get_form` but I think it's referring to `get_bcs`?

**Comment by jwallwork23** [comment]
> Thanks @jwallwork23! And one more thing... Does this also address #140? The issue mentions `get_form` but I think it's referring to `get_bcs`?

Ah yeah, that's right. Added as a linked issue.

**Review by acse-ej321 — APPROVED** [review]
@ddundo looks good.

**Comment by ddundo** [comment]
Thanks both!

**Pull request merged**
