### PR TITLE
Get `value_shape` from function spaces

### LINKED ISSUE #230: CI is failing
See e.g. https://github.com/mesh-adaptation/goalie/actions/runs/11879582630/job/33101689240.

Seems part of the Firedrake carpet has been pulled from under us. Offending errors of the form:
```
AttributeError: 'FiniteElement' object has no attribute 'value_shape'
```

### PR DESCRIPTION
**Pull request by ddundo**
Closes #230. Related to https://github.com/mesh-adaptation/animate/issues/158

### CODE REVIEW

**Comment by ddundo** [comment]
Fixed all `goalie` problems here. Only one related to https://github.com/mesh-adaptation/animate/issues/158 remains

**Review by jwallwork23 — APPROVED** [review]
Again, thanks for the quick fix.

**Comment by jwallwork23** [comment]
The Firedrake Docker env with patched Animate will get updated in the latest Action of https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/59 so will re-run tests once that's done.

**Comment by ddundo** [comment]
Thanks Joe!

**Pull request merged**
