### PR TITLE
Separate out test workflows for changed files check vs. full test suite

### PR DESCRIPTION
**Pull request by jwallwork23**
Following #197, the regular test suite run now fails: https://github.com/mesh-adaptation/goalie/actions/runs/10867321333/job/30155943577. This PR separates out the changed-files run that is used in a PR from the full test suite to run when a PR is merged into `main` or when a scheduled job is run.

It also changes the citation check workflow to not use the Docker image.

### CODE REVIEW

**Review by ddundo — APPROVED** [review]
Sorry, I meant to do this today :) as I mentioned during the meeting I was going to add `if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}` to the changed-files job and modify other if conditions to be `if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || steps.changed-files.outcome == 'success' && steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'schedule' }}
` so that we don't have 2 (almost identical) test suite workflows

**Comment by jwallwork23** [comment]
Feel free to push to this PR if you think you have something that works.

**Comment by ddundo** [comment]
I think that what I've done in `test_suite.yml` should now do what these separated workflows are doing. But feel free to keep it separated of course if that is better practice!

Also I just noticed... since we are rebuilding docker images at Sunday 1/2 AM, would it make sense to run scheduled tests after that? So that we run it on the newest container

**Comment by jwallwork23** [comment]
No if it works with one test suite workflow then that's better to avoid duplication. The reason I intervened here was to fix the broken CI.

The Docker builds are on Saturday morning so the Sunday morning test suites are indeed with fresh Docker builds.

**Comment by ddundo** [comment]
Ah sorry, I thought it was Sunday!

I now removed these separated workflows. Could you please merge if you're happy so we can see if it works on main? I'll be very embarrassed if it doesn't! :)

**Comment by jwallwork23** [comment]
Thanks @ddundo!

**Pull request merged**
