### PR TITLE
Add `CITATION.cff`

### LINKED ISSUE #115: Citing goalie and animate
Currently relevant for me. Could we add a CITATION file for goalie and animate?

### PR DESCRIPTION
**Pull request by jwallwork23**
Closes #115.

Adds a citation file so that releases work nicely with Zenodo.

Reviewers: please check you are happy with how your names are presented, that your ORCIDs are correct and present (if you have one). Feel free to push directly to the branch if you have edits.

### CODE REVIEW

**Review by ddundo — APPROVED** [review]
Thanks @jwallwork23! I added my ORCID and cancelled the workflow after seeing that the check_citation part passed.

**Comment by jwallwork23** [comment]
> Thanks @jwallwork23! I added my ORCID and cancelled the workflow after seeing that the check_citation part passed.

I wonder if there's a way to configure the CI so that it won't run if the changes aren't code changes... maybe it's too much to ask.

**Comment by ddundo** [comment]
> I wonder if there's a way to configure the CI so that it won't run if the changes aren't code changes... maybe it's too much to ask.

Well I previously suggested https://github.com/tj-actions/changed-files which could be used for this too :)

**Comment by ddundo** [comment]
> Well I previously suggested https://github.com/tj-actions/changed-files which could be used for this too :) 

I think this is fun so I'd be happy to open a PR with it and then you can feel free to reject it :) it's not a lot of work anyway

**Comment by jwallwork23** [comment]
@acse-ej321 do you have an ORCID to add or can we merge this?

**Review by acse-ej321 — APPROVED** [review]

**Pull request merged**
